package interpreter

type TokenType int

const (
	TOKEN_EOF TokenType = iota
	TOKEN_IDENT
	TOKEN_STRING
	TOKEN_NUMBER
	TOKEN_LPAREN
	TOKEN_RPAREN
	TOKEN_LBRACE
	TOKEN_RBRACE
	TOKEN_LBRACKET
	TOKEN_RBRACKET
	TOKEN_SEMICOLON
	TOKEN_COMMA
	TOKEN_DOT
	TOKEN_COLON
	TOKEN_EQ
	TOKEN_EQEQ
	TOKEN_NEQ
	TOKEN_LT
	TOKEN_GT
	TOKEN_LTE
	TOKEN_GTE
	TOKEN_PLUS
	TOKEN_MINUS
	TOKEN_STAR
	TOKEN_SLASH
	TOKEN_PERCENT
	TOKEN_PLUS_EQ
	TOKEN_MINUS_EQ
	TOKEN_AND
	TOKEN_OR
	TOKEN_NOT
	TOKEN_ARROW
)

var tokenNames = map[TokenType]string{
	TOKEN_EOF: "EOF", TOKEN_IDENT: "IDENT", TOKEN_STRING: "STRING",
	TOKEN_NUMBER: "NUMBER", TOKEN_LPAREN: "(", TOKEN_RPAREN: ")",
	TOKEN_LBRACE: "{", TOKEN_RBRACE: "}", TOKEN_LBRACKET: "[", TOKEN_RBRACKET: "]",
	TOKEN_SEMICOLON: ";", TOKEN_COMMA: ",", TOKEN_DOT: ".", TOKEN_COLON: ":",
	TOKEN_EQ: "=", TOKEN_EQEQ: "==", TOKEN_NEQ: "!=",
	TOKEN_LT: "<", TOKEN_GT: ">", TOKEN_LTE: "<=", TOKEN_GTE: ">=",
	TOKEN_PLUS: "+", TOKEN_MINUS: "-", TOKEN_STAR: "*", TOKEN_SLASH: "/", TOKEN_PERCENT: "%",
	TOKEN_PLUS_EQ: "+=", TOKEN_MINUS_EQ: "-=",
	TOKEN_AND: "&&", TOKEN_OR: "||", TOKEN_NOT: "!", TOKEN_ARROW: "->",
}

type Token struct {
	Type  TokenType
	Value string
	Line  int
	Col   int
}
